#!/bin/sh
#

script=$(basename "$0")

fail() {
	echo "$script: pre-commit hook failed" >&2
	exit 1
}

cargo fmt --check && \
cargo clippy --no-deps --no-default-features -- -Dwarnings && \
cargo clippy --no-deps --no-default-features --features ssl -- -Dwarnings && \
cargo clippy --no-deps --no-default-features --features ssl-native-tls -- -Dwarnings && \
cargo clippy --no-deps --no-default-features --features ssl-rustls -- -Dwarnings && \
cargo clippy --no-deps --no-default-features --features log -- -Dwarnings && \
cargo clippy --no-deps --no-default-features --features socket2 -- -Dwarnings && \
cargo clippy --no-deps --features ssl -- -Dwarnings && \
cargo clippy --no-deps --features ssl-native-tls -- -Dwarnings && \
cargo clippy --no-deps --features ssl-rustls -- -Dwarnings || fail

