on: [push, pull_request]
name: CI
jobs:
  clippy_rustfmt:
    name: Lint & Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        no-default-features:
          - --no-default-features
          - ''
        features:
          - ''
          - --features log
          - --features socket2
          - --features ssl-openssl
          - --features ssl-rustls
          - --features ssl-native-tls
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Clippy
        run: cargo clippy ${{ matrix.no-default-features }} ${{ matrix.features }}

      - name: Format
        run: cargo fmt -- --check

  test_log:
    name: Build & Test log feature
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.60
        features:
          - ''
          - native_tls
          - ssl
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: cargo build --release --no-default-features --features log,${{ matrix.features }}

      - name: Test
        run: cargo test --no-default-features --features log,${{ matrix.features }}

  test_native_tls:
    name: Build & Test native_tls feature
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.60
        features:
          - ''
          - log
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: cargo build --release --no-default-features --features ssl-native-tls,${{ matrix.features }}

      - name: Test
        run: cargo test --no-default-features --features ssl-native-tls,${{ matrix.features }}

  test_rustls:
    name: Build & Test rustls feature
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.61
        features:
          - ''
          - log
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: cargo build --release --no-default-features --features ssl-rustls,${{ matrix.features }}

      - name: Test
        run: cargo test --no-default-features --features ssl-rustls,${{ matrix.features }}

  test_socket2:
    name: Build & Test socket2 feature
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.63
        features:
          - ''
          - log
          - native_tls
          - rustls
          - ssl
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: cargo build --release --no-default-features --features ssl,${{ matrix.features }}

      - name: Test
        run: cargo test --no-default-features --features ssl,${{ matrix.features }}

  test_ssl:
    name: Build & Test ssl feature
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.60
        features:
          - ''
          - log
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: cargo build --release --no-default-features --features ssl,${{ matrix.features }}

      - name: Test
        run: cargo test --no-default-features --features ssl,${{ matrix.features }}
